import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  requestsContainer: {
    backgroundColor: '#f5f7fa',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#2D4E85',
  },
  requestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  requestName: {
    fontSize: 16,
    color: '#2D4E85',
    flex: 1,
  },
  gradientBackground: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingTop: 40,
  },
  narrowContainer: {
    width: '80%',
    alignSelf: 'center',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  searchBar: {
    flex: 1,
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    backgroundColor: '#f9f9f9',
  },
  clearButton: {
    marginLeft: -36,
    padding: 8,
  },
  clearButtonText: {
    fontSize: 20,
    color: '#888',
  },
  listContainer: {
    paddingHorizontal: 16,
  },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    justifyContent: 'space-between',
  },
  friendName: {
    flex: 1,
    fontSize: 16,
  },
  text: {
    fontSize: 16,
    color: '#2D4E85',
  },
  friendNameLink: {
    color: '#2D4E85',
    textDecorationLine: 'underline',
  },
  button: {
    marginLeft: 8,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 6,
    minWidth: 60,
    alignItems: 'center',
  },
  buttonAdd: {
    backgroundColor: '#4CAF50',
  },
  buttonRemove: {
    backgroundColor: '#F44336',
  },
  buttonNeutral: {
    backgroundColor: '#888',
  },
  buttonDisabled: {
    backgroundColor: '#ccc',
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  buttonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 24,
    minWidth: 260,
    alignItems: 'center',
  },
  modalText: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  snackbar: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 40,
    backgroundColor: '#323232',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  snackbarText: {
    color: '#fff',
    fontSize: 15,
    flex: 1,
  },
  snackbarAction: {
    color: '#90caf9',
    fontWeight: 'bold',
    marginLeft: 16,
    fontSize: 15,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    marginTop: 8,
    color: '#2D4E85',
  },
  searchResults: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 8,
    fontStyle: 'italic',
  },
  searchHint: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
  },
  highlightedText: {
    backgroundColor: '#ffeb3b',
    fontWeight: 'bold',
    color: '#1976d2',
  },
    // Profile modal styles
  profileModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileModalContent: {
    minWidth: 320,
    borderRadius: 22,
    paddingVertical: 36,
    paddingHorizontal: 28,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1.5,
    borderColor: '#e0e6f0',
    shadowColor: '#1a237e',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  profileModalUsername: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 12,
    letterSpacing: 1.2,
    color: '#2D4E85',
    textShadowColor: '#e3eafc',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  profileModalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#f5f7fa',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    shadowColor: '#e3eafc',
    shadowOpacity: 0.12,
    shadowRadius: 4,
    marginTop: 2,
  },
  profileModalLabel: {
    fontSize: 16,
    marginRight: 12,
    color: '#607d8b',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  profileModalValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1976d2',
    letterSpacing: 0.5,
  },
  profileModalCloseButton: {
    marginTop: 24,
    alignSelf: 'stretch',
    borderRadius: 8,
    backgroundColor: '#2D4E85',
  },
    profileModalAvatarContainer: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: '#e3eafc',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#b6c6e3',
    overflow: 'hidden',
    shadowColor: '#1a237e',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  profileModalAvatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    resizeMode: 'cover',
  },
});

export default styles;
